# Linux Transfer Learning notebook

## Datasets

Downloading the datasets : 

In [1]:
!wget http://37.187.140.181/transfer_linux_dataset/dataset_413.pkl -P ./datasets

--2020-07-17 14:08:35--  http://37.187.140.181/transfer_linux_dataset/dataset_413.pkl
Connecting to 37.187.140.181:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1172624252 (1.1G) [application/octet-stream]
Saving to: ‘./datasets/dataset_413.pkl’

dataset_413.pkl     100%[===================>]   1.09G  1.07GB/s    in 1.0s    

2020-07-17 14:08:36 (1.07 GB/s) - ‘./datasets/dataset_413.pkl’ saved [1172624252/1172624252]



In [2]:
!wget http://37.187.140.181/transfer_linux_dataset/dataset_415.pkl -P ./datasets

--2020-07-17 14:08:49--  http://37.187.140.181/transfer_linux_dataset/dataset_415.pkl
Connecting to 37.187.140.181:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 512292332 (489M) [application/octet-stream]
Saving to: ‘./datasets/dataset_415.pkl’

dataset_415.pkl     100%[===================>] 488.56M   950MB/s    in 0.5s    

2020-07-17 14:08:49 (950 MB/s) - ‘./datasets/dataset_415.pkl’ saved [512292332/512292332]



Importing the pickle files into dataframes : 

In [3]:
import pandas as pd
df_413 = pd.read_pickle("datasets/dataset_413.pkl")
df_415 = pd.read_pickle("datasets/dataset_415.pkl")

In [4]:
df_413

X86_LOCAL_APIC  OPENVSWITCH  TEXTSEARCH_FSM  LOCKDEP_SUPPORT  \
14758                1            0               0                1   
14759                1            0               0                1   
14760                1            0               0                1   
14761                1            0               0                1   
14762                1            0               0                1   
...                ...          ...             ...              ...   
110846               1            0               0                1   
110847               1            0               0                1   
110848               1            0               0                1   
110849               1            1               1                1   
110850               1            0               0                1   

        GENERIC_CLOCKEVENTS_MIN_ADJUST  NETFILTER_XT_MATCH_TCPMSS  MPLS  \
14758                                1                          0     1   
14759                                1                          0     0   
14760                                1                          0     0   
14761                                1                          0     0   
14762                                1                          0     0   
...                                ...                        ...   ...   
110846                               1                          0     0   
110847                               1                          0     0   
110848                               1                          0     0   
110849                               1                          0     1   
110850                               1                          0     0   

        NFC_HCI  STACKTRACE_SUPPORT  GENERIC_CMOS_UPDATE  ...  LZO-vmlinux  \
14758         0                   1                    1  ...     11008072   
14759         0                   1                    1  ...      6603288   
14760         0                   1                    1  ...     14475800   
14761         0                   1                    1  ...     10867576   
14762         1                   1                    1  ...     20018040   
...         ...                 ...                  ...  ...          ...   
110846        2                   1                    1  ...      6582808   
110847        0                   1                    1  ...      9269784   
110848        1                   1                    1  ...     13136760   
110849        0                   1                    1  ...     11907608   
110850        0                   1                    1  ...      8209272   

             LZO  LZ4-bzImage  LZ4-vmlinux       LZ4     cid  nbyes   nbno  \
14758    8734199    9839568.0     11925896   9638560   30000   1435  10346   
14759    4385061    4838864.0      6923096   4693085   30001   1382  10012   
14760   12256864   13362640.0     15446872  13214970   30002   1626  10852   
14761    8647251    9302992.0     11388080   9155423   30003   2140  10338   
14762   17796721   19346384.0     21431472  19197696   30004   2651   9827   
...          ...          ...          ...       ...     ...    ...    ...   
110846   4364968    4793296.0      6878040   4647107  126741   1113  10693   
110847   7051800    7668176.0      9753432   7523253  126742   2253  10225   
110848  10915039   11722704.0     13808816  11577709  126743   2627   9851   
110849   9688845   10469840.0     12555096  10326671  126744   1775   9674   
110850   5988832    6554576.0      8639664   6405336  126753   1156  10866   

        nbmodule  nbyesmodule  
14758        697         2132  
14759       1084         2466  
14760          0         1626  
14761          0         2140  
14762          0         2651  
...          ...          ...  
110846       672         1785  
110847         0         2253  
110848         0         2627  
110849      1029         2804  
110850       456

In [5]:
df_415

NETFILTER_XT_MATCH_CONNMARK  NET_EMATCH  SDLA  TOUCHSCREEN_AD7877  \
1                                0           0     0                   0   
2                                0           0     0                   0   
3                                0           0     0                   1   
4                                0           0     0                   0   
5                                0           0     0                   0   
...                            ...         ...   ...                 ...   
39842                            0           0     0                   0   
39843                            0           0     0                   0   
39844                            0           0     0                   0   
39845                            0           0     0                   0   
39846                            0           0     0                   0   

       SERIAL_8250_EXAR_ST16C554  REGULATOR_88PM8607  DVB_USB_CXUSB  \
1                              0                   1              0   
2                              0                   0              0   
3                              0                   0              0   
4                              0                   0              0   
5                              0                   0              0   
...                          ...                 ...            ...   
39842                          0                   0              0   
39843                          0                   0              0   
39844                          0                   1              0   
39845                          0                   0              0   
39846                          0                   0              0   

       CRYPTO_SHA512_MB  NETFILTER_XT_MATCH_CONNTRACK  LAPBETHER  ...  \
1                     1                             0          0  ...   
2                     0                             0          0  ...   
3                     1                             0          0  ...   
4                     0                             0          0  ...   
5                     0                             0          0  ...   
...                 ...                           ...        ...  ...   
39842                 1                             0          0  ...   
39843                 0                             0          0  ...   
39844                 1                             0          0  ...   
39845                 0                             0          0  ...   
39846                 1                             0          0  ...   

       XZ-vmlinux        XZ  LZO-bzImage  LZO-vmlinux       LZO  LZ4-bzImage  \
1         9791464   7554872     12787888     14874088  12650651     13766832   
2         9766192   7453912     12244240     14332720  12029959     13612304   
3        15259176  13024548     21803600     23888936  21666603     23593552   
4         7718672   5487408      9552944     11638024   9415719     10482736   
5         9209616   6979100     11936816     14021896  11802122     12969008   
...           ...       ...          ...          ...       ...          ...   
39842     5221256   2925332      4867024      6953352   4668518      5411792   
39843     7120656   4890576      8368176     10454280   8233143      9170992   
39844    17857680  15560416     28881456     30968456  28683704     32551472   
39845     8165040   5931960     10577360     12661928  10443053     11613648   
39846     6461320   4222564      7020624      9106816   6881019      7667792   

       LZ4-vmlinux       LZ4    cid  nbyes  
1         15853424  13618427  29787   1368  
2         15701184  13389490  29788   2490  
3         25679288  23445627  29789   1991  
4         12568216  10336659  29790   1614  
5         15054488  12822792  29791   1289  
...            ...       ...    ...    ...  
39842      7498512   5202868  69996   1110  
39843     11257496   9023391  69997   1429 

## Solving features shifting

In [6]:
columns_413 = set(df_413.columns.values)
columns_415 = set(df_415.columns.values)

print("Number of features in 4.13 dataset : ", len(columns_413))
print("Number of features in 4.15 dataset : ", len(columns_415))
print("Number of features common to both datasets : ", len(columns_413.intersection(columns_415)))

Number of features in 4.13 dataset :  12502
Number of features in 4.15 dataset :  12850
Number of features common to both datasets :  12411


We can see that some features appear in 4.15, and other disappear.

In [7]:
print("Number of features that disappear in 4.15 : ", len(columns_413.difference(columns_415)))
print("Number of features that appear in 4.15 : ", len(columns_415.difference(columns_413)))

Number of features that disappear in 4.15 :  91
Number of features that appear in 4.15 :  439


If we want to align the 4.15 dataset to the 4.13 dataset, we have to perform 2 operations : 
 * Delete "new" features
 * Assign a value to the "old" features

Eliminating the new features is quite easy, only select the features intersection : 

In [8]:
df_415_reduced = df_415[columns_413.intersection(columns_415)]

To assign a value for all old features, we need to create the columns one by one and to decide which value to take. Here we will asign the value 1, the other possibility would be 0.

In [31]:
for c in columns_413.difference(columns_415):
    df_415_reduced = df_415_reduced.assign(**{c:1})

In [32]:
df_415_reduced

MV643XX_ETH  NETCONSOLE  SND_MPU401  KERNEL_XZ  BSD_PROCESS_ACCT  \
1                0           0           0          0                 0   
2                0           0           0          0                 0   
3                0           0           0          0                 0   
4                0           0           0          0                 0   
5                0           1           0          0                 0   
...            ...         ...         ...        ...               ...   
39842            0           0           0          0                 0   
39843            0           0           0          0                 1   
39844            0           0           1          0                 1   
39845            0           0           0          0                 1   
39846            0           0           0          0                 1   

       SENSORS_F71805F  SND_AD1816A  BLK_CGROUP  SND_SOC_PCM179X_SPI  \
1                    0            0           0                    0   
2                    1            0           0                    0   
3                    1            0           1                    0   
4                    0            0           0                    0   
5                    0            0           0                    0   
...                ...          ...         ...                  ...   
39842                0            0           0                    0   
39843                1            0           0                    0   
39844                1            0           0                    1   
39845                1            0           1                    0   
39846                1            0           0                    0   

       VIDEO_USBTV  ...  SOUND_TRACEINIT  CRYPTO_DEV_MV_CESA  \
1                0  ...                1                   1   
2                0  ...                1                   1   
3                0  ...                1                   1   
4                1  ...                1                   1   
5                0  ...                1                   1   
...            ...  ...              ...                 ...   
39842            0  ...                1                   1   
39843            0  ...                1                   1   
39844            0  ...                1                   1   
39845            0  ...                1                   1   
39846            0  ...                1                   1   

       USB_QCOM_8X16_PHY  VIDEO_GC0310  CISS_SCSI_TAPE  \
1                      1             1               1   
2                      1             1               1   
3                      1             1               1   
4                      1             1               1   
5                      1             1               1   
...                  ...           ...             ...   
39842                  1             1               1   
39843                  1             1               1   
39844                  1             1               1   
39845                  1             1               1   
39846                  1             1               1   

       GENERIC_TIME_VSYSCALL_OLD  ARM_MT8173_CPUFREQ  TRIX_HAVE_BOOT  \
1                              1                   1               1   
2                              1                   1               1   
3                              1                   1               1   
4                              1                   1               1   
5                              1                   1               1   
...                          ...                 ...             ...   
39842                          1                   1               1   
39843                          1                   1               1   
39844                          1                   1               1   
39845                          1                   1   

In [33]:
print("Number of features common to 4.13 dataset and the aligned 4.15 dataset : ", len(columns_413.intersection(df_415_reduced)))

Number of features common to 4.13 dataset and the aligned 4.15 dataset :  12502


Reordering the new 4.15 dataset : 

In [34]:
df_415_reduced = df_415_reduced[df_413.columns]

In [35]:
df_415_reduced

X86_LOCAL_APIC  OPENVSWITCH  TEXTSEARCH_FSM  LOCKDEP_SUPPORT  \
1                   1            0               0                1   
2                   1            0               0                1   
3                   1            0               0                1   
4                   1            0               0                1   
5                   1            1               0                1   
...               ...          ...             ...              ...   
39842               1            0               0                1   
39843               1            0               0                1   
39844               1            0               0                1   
39845               1            0               0                1   
39846               1            0               0                1   

       GENERIC_CLOCKEVENTS_MIN_ADJUST  NETFILTER_XT_MATCH_TCPMSS  MPLS  \
1                                   1                          0     1   
2                                   1                          0     1   
3                                   1                          0     0   
4                                   1                          0     0   
5                                   1                          0     1   
...                               ...                        ...   ...   
39842                               1                          0     1   
39843                               1                          0     0   
39844                               1                          0     0   
39845                               1                          0     0   
39846                               1                          0     0   

       NFC_HCI  STACKTRACE_SUPPORT  GENERIC_CMOS_UPDATE  ...  LZO-vmlinux  \
1            1                   1                    1  ...     14874088   
2            0                   1                    1  ...     14332720   
3            0                   1                    1  ...     23888936   
4            0                   1                    1  ...     11638024   
5            0                   1                    1  ...     14021896   
...        ...                 ...                  ...  ...          ...   
39842        0                   1                    1  ...      6953352   
39843        0                   1                    1  ...     10454280   
39844        0                   1                    1  ...     30968456   
39845        0                   1                    1  ...     12661928   
39846        0                   1                    1  ...      9106816   

            LZO  LZ4-bzImage  LZ4-vmlinux       LZ4    cid  nbyes  nbno  \
1      12650651     13766832     15853424  13618427  29787   1368     1   
2      12029959     13612304     15701184  13389490  29788   2490     1   
3      21666603     23593552     25679288  23445627  29789   1991     1   
4       9415719     10482736     12568216  10336659  29790   1614     1   
5      11802122     12969008     15054488  12822792  29791   1289     1   
...         ...          ...          ...       ...    ...    ...   ...   
39842   4668518      5411792      7498512   5202868  69996   1110     1   
39843   8233143      9170992     11257496   9023391  69997   1429     1   
39844  28683704     32551472     34638872  32340626  69998   2780     1   
39845  10443053     11613648     13698616  11465752  69999   1704     1   
39846   6881019      7667792      9754384   7515896  70000   1120     1   

       nbmodule  nbyesmodule  
1             1            1  
2             1            1  
3             1            1  
4             1            1  
5             1            1  
...         ...          ...  
39842         1            1  
39843         1            1  
39844         1            1  
39845         1            1  
39846         1            1  

[39370 rows x 12502 columns]